### ISSUE TITLE
Could not create widget Ratings.widget.ratings_nologic (Mx 7.17.2)

### ISSUE THREAD

**Issue by RickZwaal** [mendix/Ratings#12]
Hi,

The Widget isn't working anymore in version: Mx 7.17.2. Seems the logger.level isn't available anymore on the client side. Without this function widget seems to work.

Can this be fixed?

BR,
Rick

**Comment by JelteMX** [comment]
This was fixed in version 1.6.2 or 1.6.1. Currently we're at 1.6.5. Please update the widget from the App Store and try again. `logger.level` is not called anywhere in the latest version.
