### ISSUE TITLE
Images not visible in Sandbox

### ISSUE THREAD

**Issue by MxSinan** [mendix/Ratings#4]
Guys, after the release of last time I see that the rating images (stars) are not visible in a Sandbox environment, while they are visible local. Therefore i think that url's of the rating images are broken. Could someone check this please? thanks sinan

**Comment by JelteMX** [comment]
Reference to the [forum post](https://mxforum.mendix.com/questions/19932/Image-in-rating-widget-is-not-visible-when-running-in-Sandbox). Going to check this out this/next week

**Comment by JelteMX** [comment]
Confirmed bug

**Comment by MxSinan** [comment]
Solution works, thnx Jelte.
