### ISSUE TITLE
Could not create widget

### ISSUE THREAD

**Issue by ndelord** [mendix/Ratings#5]
Hi,

After migrating to Mx6 and updating the widget with the last version on the app store and github, I get the following error:

Could not create widget Ratings.widget.ratings_nologic: Error: Invalid template:

**Comment by akileng56** [comment]
The cause of that isssue is that the TemplatedMixin does not find an Html template to use for creating dom node.
check https://github.com/mendix/Ratings/blob/master/src/Ratings/widget/ratings_nologic.js#L13

solution:
- Add this bit of code: templateString: widgetTemplate,

I will be creating a pull request soon..

**Comment by JelteMX** [comment]
Thanks for analysing. If you have a pull request, I'll review, merge and update it next week

**Comment by JelteMX** [comment]
Added to [1.6.3](https://github.com/mendix/Ratings/releases/tag/v1.6.3), will update in the AppStore today/tomorrow
