### ISSUE TITLE
Default to 1 star

### ISSUE THREAD

**Issue by ndelord** [mendix/Ratings#7]
Thanks for fixing the template issue.
However, I can see a regression. The widget defaults to 1 star. It was empty (0) in the version I was using on Mendix 5.

**Comment by tieniber** [comment]
Just was able to reproduce. Fix pending.

**Comment by tieniber** [comment]
Nico, can you please test this widget:

https://github.com/tieniber/Ratings/blob/master/test/widgets/Ratings.mpk?raw=true

Please let me know if that works. If it does, I'll create a pull request so we can close this ticket.

**Comment by tieniber** [comment]
#9

**Comment by JelteMX** [comment]
Fixed in [1.6.4](https://github.com/mendix/Ratings/releases/tag/v1.6.4), thanks for the PR @tieniber
